# Generated by Django 3.2.8 on 2022-04-19 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_comment_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent',
            new_name='parents_id',
        ),
    ]
